# Curso sobre Numpy

In [1]:
import torch
import numpy as np

## Instaciando tensores a partir de matrizes python

In [13]:
lista = [
    [1,2,3],
    [4,5,6]
]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

print("\n")
tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

print("\n")
tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

print("\n")
tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

print("\n")
tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)



torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## Instaciando tensores a partir do NumPy 
**(Assim preserva o tipo do ndarray numpy)**

In [3]:
arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print("{} => {}\n".format(type(arr), arr))
print("{} => {}\n".format(type(tns), tns))

<class 'numpy.ndarray'> => [[0.82158894 0.29312281 0.95882138 0.36443957]
 [0.78881708 0.4736249  0.07925509 0.18295334]
 [0.93442373 0.89704459 0.06113969 0.39516083]]

<class 'torch.Tensor'> => tensor([[0.8216, 0.2931, 0.9588, 0.3644],
        [0.7888, 0.4736, 0.0793, 0.1830],
        [0.9344, 0.8970, 0.0611, 0.3952]], dtype=torch.float64)



## Tensores inicializados

In [4]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.0751, -0.3793,  0.7479],
        [-0.2786,  0.9234,  0.0902],
        [ 0.3424, -0.1556, -0.0043]])


## Tensor para array Numpy

In [5]:
arr = tnsr.data.numpy()
print(arr)
print(type(arr))

[[ 0.07511143 -0.37934506  0.74794936]
 [-0.27858204  0.9233658   0.09018133]
 [ 0.34244385 -0.15556625 -0.00430131]]
<class 'numpy.ndarray'>


## Indexação

In [6]:
print(tnsr)
tnsr[0,2] = -22

print('\n')
print(tnsr)

print('\n')
print("Fatia do meu tensor")
print("=======================")
print(tnsr[0:2])

print('\n')
print("Fatia do meu tensor")
print("=======================")
print(tnsr[0:2, 0:2])

tensor([[ 0.0751, -0.3793,  0.7479],
        [-0.2786,  0.9234,  0.0902],
        [ 0.3424, -0.1556, -0.0043]])


tensor([[ 7.5111e-02, -3.7935e-01, -2.2000e+01],
        [-2.7858e-01,  9.2337e-01,  9.0181e-02],
        [ 3.4244e-01, -1.5557e-01, -4.3013e-03]])


Fatia do meu tensor
tensor([[  0.0751,  -0.3793, -22.0000],
        [ -0.2786,   0.9234,   0.0902]])


Fatia do meu tensor
tensor([[ 0.0751, -0.3793],
        [-0.2786,  0.9234]])


#### NOTA DE AULA

- Os tensores são **mutáveis**
- Podem executar operações aritméticas, **desde que tenham os mesmos shapes**

## Funções size() e view()

```python
<torch.Tensor>.view() # Equivale ao reshape do Numpy
```


In [7]:
tns3d = torch.randn(2,2,3)
print(tns1.size())
print(tns3d.view(12))


torch.Size([2, 3])
tensor([-1.6332, -1.0785, -0.8780,  0.8524, -1.9122, -0.7306,  3.6712,  1.4743,
        -1.3050,  0.4749,  0.0141, -0.1655])


## GPU Cast

In [15]:
if torch.has_mps:
    print("It's available MPS!")
    device = torch.device('mps')
else:
    print("It's available CPU!")
    device = torch.device('cpu')
    
print(device)

a = torch.ones(2, 3, 4, device=device)
print(a * 2)


It's available MPS!
mps
tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]], device='mps:0')
